In [1]:
import pandas as pd

In [3]:
transaction = pd.read_csv('Transaction.csv')

In [4]:
transaction

,Transaction_id,customer_id,Date,Product,Gender,Device_Type,Category,Customer_Login_type,Delivery_Type,Quantity,Amount US$,Individual_Price_US$
0,40170,1348959766,11/14/2013,Hair Band,Female,Web,Accessories,Member,one-day deliver,12,"6,910",576
1,76028,1645228017,12/21/2013,Jean,Female,Web,Clothing,Guest,one-day deliver,16,641,40
2,17894,1610000572,10/10/2013,Shirt,Male,Web,Clothing,Member,one-day delivery,12,"1,647",137
3,17949,2217960309,10/10/2013,Shirt,Male,Web,Clothing,Member,one-day deliver,17,0,0
4,17951,2219304866,10/10/2013,Shirts,Male,Web,Clothing,Member,one-day deliver,22,"5,298",241
5,18016,1980331295,10/10/2013,Shirt,Male,Web,Clothing,Member,one-day deliver,19,"4,509",237
6,18902,1847892475,10/12/2013,Shirt,Male,Web,Clothing,Member,one-day deliver,20,0,0
7,18967,1649911553,10/13/2013,Shirt,Male,Web,Clothing,Member,one-day deliver,17,"1,499",88
8,19180,1903809905,10/13/2013,Shirt,Male,Web,Clothing,Member,one-day delivery,16,"2,000",125
9,19203,1411855932,10/13/2013,Shirts,Male,Web,Clothing,Member,one-day delivery,21,"3,260",155
10,19340,1769953196,10/13/2013,Shirts,Male,Web,Clothing,Member,one-day delivery,19,"17,837",939
11,19404,1568148818,10/14/2013,Shirts,Male,Web,Clothing,Member,one-day delivery,14,"1,016",73
12,19427,1751652831,10/14/2013,Shirts,Male,Web,Clothing,Member,one-day delivery,14,"4,628",331
13,19592,2231859892,10/14/2013,Shirts,Male,Web,Clothing,Member,one-day deliver,20,570,29
14,19932,1535745421,10/15/2013,Shirt,Male,Web,Clothing,Member,one-day deliver,12,"3,000",250
15,20055,1922087137,10/15/2013,Shirt,Male,Web,Clothing,Member,one-day deliver,22,"5,573",253
16,20315,2262467094,10/15/2013,Shirt,Male,Web,Clothing,Member,one-day deliver,19,"5,349",282
17,20321,2268641437,10/15/2013,Shirt,Male,Web,Clothing,Member,one-day deliver,16,"2,500",156
18,20436,1727052876,10/15/2013,Shirts,Male,Web,Clothing,Member,Normal Delivery,15,"6,900",460
19,20535,1674613702,10/15/2013,Shirts,Male,Web,Clothing,Member,one-day deliver,21,"1,794",85
20,20693,1921733731,10/16/2013,Shirts,Male,Web,Clothing,Member,one-day deliver,12,"6,000",500
21,22314,1936150747,10/18/2013,Shirts,Male,Web,Clothing,Member,one-day deliver,20,584,29
22,22421,1229841159,10/18/2013,Shirt,Male,Web,Clothing,Member,one-day deliver,21,"5,217",248
23,22458,1586690479,10/19/2013,Shirt,Male,Web,Clothing,Member,one-day deliver,13,300,23
24,22682,1848085677,10/19/2013,Shirt,Male,Web,Clothing,Member,one-day deliver,16,"1,999",125
25,22740,1872369353,10/19/2013,Shirt,Male,Web,Clothing,Member,one-day deliver,16,699,44
26,22907,1519749240,10/19/2013,Shirt,Male,Web,Clothing,Member,one-day deliver,18,499,28
27,23261,1439048077,10/20/2013,Shirt,Male,Web,Clothing,Member,one-day deliver,21,"7,395",352
28,23490,1361902722,10/20/2013,Shirt,Male,Web,Clothing,Member,one-day delivery,13,"1,999",154
29,23501,1535495415,10/20/2013,Shirt,Male,Web,Clothing,Member,one-day delivery,22,299,14
...,...,...,...,...,...,...,...,...,...,...,...,...
2780,67681,2238091027,12/14/2013,Shoes,Female,Mobile,wearables,Member,one-day deliver,12,500,42
2781,67790,1628206020,12/14/2013,Shoes,Female,Mobile,wearables,Member,one-day deliver,14,"1,000",71
2782,67897,1685924134,12/14/2013,Shoes,Female,Mobile,wearables,Member,one-day deliver,12,429,36
2783,68055,1686570943,12/14/2013,Shoes,Female,Mobile,wearables,Member,one-day deliver,21,"4,326",206
2784,69322,1442018926,12/15/2013,Shoes,Female,Mobile,wearables,Member,one-day deliver,17,995,59
2785,69325,2201147779,12/15/2013,Shoes,Female,Mobile,wearables,Member,one-day deliver,14,"1,610",115
2786,69773,1229801150,12/15/2013,Shoes,Female,Mobile,wearables,Member,one-day deliver,12,"2,495",208
2787,70230,1176645739,12/16/2013,Shoes,Female,Mobile,wearables,Member,one-day deliver,12,"12,881","1,073"
2788,72667,1612949281,12/17/2013,Shoes,Female,Mobile,wearables,Member,one-day deliver,22,"2,000",91
2789,73066,1429149492,12/17/2013,Shoes,Female,Mobile,wearables,Member,Normal Delivery,21,"17,099",814
2790,73183,1252460418,12/18/2013,Shoes,Female,Mobile,wearables,Member,one-day deliver,23,"1,499",65
2791,73741,1778837865,12/18/2013,Shoes,Female,Mobile,wearables,Member,one-day deliver,21,0,0
2792,74317,2293384527,12/19/2013,Shoes,Female,Mobile,wearables,Guest,one-day deliver,21,"1,000",48
2793,75234,1178375628,12/20/2013,Shoes,Female,Mobile,wearables,Member,one-day deliver,15,0,0
2794,77362,1638141469,12/23/2013,Shoes,Female,Mobile,wearables,Member,one-day deliver,14,"23,954","1,711"
2795,78016,1915952977,12/24/2013,Shoes,Female,Mobile,wearables,Member,one-day deliver,18,"1,225",68
2796,78050,1329814703,12/24/2013,Shoes,Female,Mobile,wearables,Member,one-day deliver,18,"1,498",83
2797,78121,1329814703,12/24/2013,Shoes,Female,Mobile,wearables,Member,one-day deliver,18,"5,000",278
2798,79506,1724582223,12/26/2013,Shoes,Female,Mobile,wearables,Member,one-day deliver,13,"1,349",104
2799,79779,1273461348,12/26/2013,Shoes,Female,Mobile,wearables,Member,one-day deliver,21,"7,405",353
2800,80218,1594121463,12/27/2013,Shoes,Female,Mobile,wearables,Member,one-day deliver,15,"2,049",137
2801,80953,1678935868,12/28/2013,Shoes,Female,Mobile,wearables,Member,Normal Delivery,17,"1,199",71
2802,82436,2223609361,12/29/2013,Shoes,Female,Mobile,wearables,Member,one-day deliver,13,963,74
2803,82895,2196869116,12/30/2013,Shoes,Female,Mobile,wearables,Member,one-day deliver,16,"2,999",187
2804,84652,1163574886,1/1/2014,Shoes,Female,Mobile,wearables,Member,one-day deliver,23,"1,894",82
2805,87229,1934341369,1/4/2014,Shoes,Female,Mobile,wearables,Member,one-day deliver,13,"3,495",269
2806,91945,1506256089,1/11/2014,Shoes,Female,Mobile,wearables,Member,one-day deliver,13,"9,900",762
2807,92063,1651310842,1/11/2014,Shoes,Female,Mobile,wearables,Member,one-day deliver,23,"1,768",77
2808,92458,2152149636,1/12/2014,Shoes,Female,Mobile,wearables,Member,one-day deliver,16,"9,216",576
2809,92660,1382338268,1/12/2014,Shoes,Female,Mobile,wearables,Member,one-day deliver,16,"3,298",206

In [5]:
transaction.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2810 entries, 0 to 2809
Data columns (total 12 columns):
Transaction_id          2810 non-null int64
customer_id             2810 non-null int64
Date                    2810 non-null object
Product                 2810 non-null object
Gender                  2810 non-null object
Device_Type             2810 non-null object
Category                2810 non-null object
Customer_Login_type     2810 non-null object
Delivery_Type           2810 non-null object
Quantity                2810 non-null int64
Amount US$              2809 non-null object
Individual_Price_US$    2810 non-null object
dtypes: int64(3), object(9)
memory usage: 263.5+ KB

In [6]:
transaction_backup = transaction.copy()

In [7]:
transaction['Transaction_id'] = transaction['Transaction_id'].astype('str')

In [8]:
transaction['customer_id'] = transaction['customer_id'].astype('str')

In [9]:
transaction.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2810 entries, 0 to 2809
Data columns (total 12 columns):
Transaction_id          2810 non-null object
customer_id             2810 non-null object
Date                    2810 non-null object
Product                 2810 non-null object
Gender                  2810 non-null object
Device_Type             2810 non-null object
Category                2810 non-null object
Customer_Login_type     2810 non-null object
Delivery_Type           2810 non-null object
Quantity                2810 non-null int64
Amount US$              2809 non-null object
Individual_Price_US$    2810 non-null object
dtypes: int64(1), object(11)
memory usage: 263.5+ KB

In [10]:
transaction['Date'] = pd.to_datetime(transaction['Date'], format='%m/%d/%Y')

In [11]:
transaction['Amount US$'] = transaction['Amount US$'].str.replace(',','')

In [12]:
transaction['Amount US$']

0        6910
1         641
2        1647
3           0
4        5298
5        4509
6           0
7        1499
8        2000
9        3260
10      17837
11       1016
12       4628
13        570
14       3000
15       5573
16       5349
17       2500
18       6900
19       1794
20       6000
21        584
22       5217
23        300
24       1999
25        699
26        499
27       7395
28       1999
29        299
        ...
2780      500
2781     1000
2782      429
2783     4326
2784      995
2785     1610
2786     2495
2787    12881
2788     2000
2789    17099
2790     1499
2791        0
2792     1000
2793        0
2794    23954
2795     1225
2796     1498
2797     5000
2798     1349
2799     7405
2800     2049
2801     1199
2802      963
2803     2999
2804     1894
2805     3495
2806     9900
2807     1768
2808     9216
2809     3298
Name: Amount US$, Length: 2810, dtype: object

In [13]:
transaction = transaction.dropna(axis=0)

In [14]:
transaction.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2809 entries, 0 to 2809
Data columns (total 12 columns):
Transaction_id          2809 non-null object
customer_id             2809 non-null object
Date                    2809 non-null datetime64[ns]
Product                 2809 non-null object
Gender                  2809 non-null object
Device_Type             2809 non-null object
Category                2809 non-null object
Customer_Login_type     2809 non-null object
Delivery_Type           2809 non-null object
Quantity                2809 non-null int64
Amount US$              2809 non-null object
Individual_Price_US$    2809 non-null object
dtypes: datetime64[ns](1), int64(1), object(10)
memory usage: 285.3+ KB

In [15]:
transaction['Amount US$'] = transaction['Amount US$'].astype('int')

C:\Users\SOLAHUDIN\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [16]:
transaction['Individual_Price_US$'] = transaction['Individual_Price_US$'].str.replace(',','')

C:\Users\SOLAHUDIN\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [17]:
transaction['Individual_Price_US$'].unique()

array(['576', '40', '137', '0', '241', '237', '88', '125', '155', '939',
       '73', '331', '29', '250', '253', '282', '156', '460', '85', '500',
       '248', '23', '44', '28', '352', '154', '14', '83', '17', '170',
       '267', '131', '150', '378', '144', '169', '145', '36', '60', '473',
       '110', '359', '432', '323', '127', '53', '920', '54', '219', '117',
       '70', '11', '166', '200', '4', '100', '223', '550', '78', '298',
       '714', '329', '58', '1387', '148', '25', '133', '493', '245',
       '108', '59', '65', '1318', '455', '99', '261', '61', '94', '204',
       '231', '695', '64', '32', '859', '56', '143', '382', '130', '33',
       '50', '63', '38', '385', '775', '168', '252', '447', '102', '1497',
       '639', '81', '353', '167', '22', '115', '781', '1389', '116',
       '293', '140', '368', '#VALUE!', '80', '182', '18', '15', '123',
       '233', '297', '86', '1343', '176', '313', '306', '42', '3839',
       '95', '6', '257', '383', '243', '242', '47', '8', '341', '230',
       '138', '224', '186', '118', '180', '39', '76', '43', '21', '77',
       '128', '1040', '194', '240', '67', '114', '135', '163', '644',
       '229', '1583', '188', '174', '89', '358', '311', '1036', '283',
       '308', '112', '348', '45', '134', '942', '202', '251', '106',
       '325', '13', '124', '205', '907', '91', '79', '122', '787', '694',
       '386', '300', '71', '474', '770', '9', '195', '333', '107', '239',
       '950', '105', '3972', '316', '82', '62', '840', '334', '364',
       '375', '126', '541', '2361', '41', '768', '272', '808', '1516',
       '285', '307', '1399', '366', '55', '700', '12', '336', '119',
       '157', '469', '2923', '2386', '1111', '457', '357', '509', '400',
       '26', '1566', '3667', '892', '271', '153', '483', '309', '206',
       '1167', '187', '349', '30', '1114', '147', '37', '683', '494',
       '625', '304', '614', '403', '211', '31', '2143', '97', '120',
       '584', '340', '480', '213', '459', '466', '235', '103', '210',
       '2258', '1570', '1106', '162', '529', '553', '351', '34', '335',
       '68', '667', '343', '295', '69', '918', '408', '444', '498',
       '3228', '264', '93', '884', '209', '1209', '238', '1028', '1703',
       '51', '228', '278', '871', '319', '1471', '19', '669', '1592',
       '436', '310', '1599', '225', '332', '172', '35', '600', '289',
       '568', '181', '567', '497', '941', '563', '1667', '464', '74',
       '87', '658', '800', '256', '388', '215', '708', '833', '354',
       '434', '113', '72', '485', '633', '381', '536', '733', '27', '585',
       '450', '299', '1208', '735', '390', '339', '2500', '10', '350',
       '234', '515', '344', '539', '678', '288', '315', '746', '1855',
       '337', '84', '461', '1796', '132', '312', '192', '1429', '392',
       '57', '318', '582', '5', '96', '2750', '729', '1150', '2864',
       '196', '439', '159', '611', '1227', '183', '48', '535', '328',
       '428', '286', '557', '3', '513', '322', '443', '212', '766', '226',
       '1103', '121', '476', '136', '1176', '198', '7', '185', '650',
       '247', '236', '75', '20', '178', '1571', '52', '191', '663', '413',
       '269', '662', '305', '1475', '152', '3632', '273', '16', '111',
       '158', '208', '1406', '989', '173', '998', '684', '399', '792',
       '367', '706', '92', '984', '802', '109', '1633', '445', '3026',
       '222', '1250', '417', '189', '1135', '175', '796', '324', '441',
       '49', '507', '405', '458', '710', '556', '24', '255', '214', '1',
       '1423', '1006', '816', '342', '141', '190', '146', '262', '321',
       '199', '216', '825', '2333', '1252', '139', '265', '858', '1207',
       '217', '142', '672', '767', '530', '418', '842', '184', '421',
       '1056', '937', '410', '583', '566', '276', '481', '424', '177',
       '1024', '218', '640', '275', '426', '66', '2415', '599', '284',
       '302', '709', '2069', '259', '149', '685', '1896', '268', '2228',
       '809', '277', '831', '1062', '832', '3279', '314', '565', '478',
       '129', '609', '165', '1211', '569', '1076', '244', '1854', '1212',
       '1113', '608', '885', '1136', '1138', '1674', '438', '456', '427',
       '151', '266', '2279', '776', '4667', '558', '641', '303', '347',
       '628', '2826', '677', '395', '294', '291', '588', '805', '525',
       '607', '467', '346', '572', '3218', '1086', '623', '4730', '617',
       '90', '1204', '1183', '544', '292', '179', '171', '376', '676',
       '1546', '287', '604', '900', '2896', '838', '772', '290', '472',
       '429', '1943', '1660', '279', '263', '1110', '220', '828', '104',
       '327', '470', '671', '945', '518', '591', '201', '46', '1286',
       '320', '1424', '2683', '854', '679', '875', '2015', '502', '5700',
       '281', '164', '889', '394', '2264', '613', '301', '631', '414',
       '98', '898', '538', '895', '927', '365', '968', '1874', '692',
       '374', '391', '1079', '258', '935', '1323', '731', '449', '4944',
       '1013', '2769', '590', '227', '1620', '296', '643', '203', '2153',
       '280', '867', '420', '161', '380', '839', '804', '956', '719',
       '705', '581', '1911', '1154', '488', '1178', '2', '577', '274',
       '317', '1153', '411', '422', '389', '431', '1047', '795', '2191',
       '1513', '387', '652', '635', '384', '1007', '433', '101', '822',
       '1041', '552', '416', '1904', '1093', '2470', '533', '2038', '847',
       '496', '465', '864', '2000', '249', '491', '516', '1229', '270',
       '377', '1448', '419', '1019', '682', '356', '1186', '722', '868',
       '193', '446', '645', '1134', '648', '369', '254', '1233', '532',
       '1232', '1073', '814', '1711', '762'], dtype=object)

In [18]:
transaction = transaction[transaction['Individual_Price_US$']!='#VALUE!']

In [19]:
transaction['Individual_Price_US$'] = transaction['Individual_Price_US$'].astype('int')

In [20]:
transaction.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2798 entries, 0 to 2809
Data columns (total 12 columns):
Transaction_id          2798 non-null object
customer_id             2798 non-null object
Date                    2798 non-null datetime64[ns]
Product                 2798 non-null object
Gender                  2798 non-null object
Device_Type             2798 non-null object
Category                2798 non-null object
Customer_Login_type     2798 non-null object
Delivery_Type           2798 non-null object
Quantity                2798 non-null int64
Amount US$              2798 non-null int32
Individual_Price_US$    2798 non-null int32
dtypes: datetime64[ns](1), int32(2), int64(1), object(8)
memory usage: 262.3+ KB

In [21]:
transaction.drop_duplicates()

,Transaction_id,customer_id,Date,Product,Gender,Device_Type,Category,Customer_Login_type,Delivery_Type,Quantity,Amount US$,Individual_Price_US$
0,40170,1348959766,2013-11-14,Hair Band,Female,Web,Accessories,Member,one-day deliver,12,6910,576
1,76028,1645228017,2013-12-21,Jean,Female,Web,Clothing,Guest,one-day deliver,16,641,40
2,17894,1610000572,2013-10-10,Shirt,Male,Web,Clothing,Member,one-day delivery,12,1647,137
3,17949,2217960309,2013-10-10,Shirt,Male,Web,Clothing,Member,one-day deliver,17,0,0
4,17951,2219304866,2013-10-10,Shirts,Male,Web,Clothing,Member,one-day deliver,22,5298,241
5,18016,1980331295,2013-10-10,Shirt,Male,Web,Clothing,Member,one-day deliver,19,4509,237
6,18902,1847892475,2013-10-12,Shirt,Male,Web,Clothing,Member,one-day deliver,20,0,0
7,18967,1649911553,2013-10-13,Shirt,Male,Web,Clothing,Member,one-day deliver,17,1499,88
8,19180,1903809905,2013-10-13,Shirt,Male,Web,Clothing,Member,one-day delivery,16,2000,125
9,19203,1411855932,2013-10-13,Shirts,Male,Web,Clothing,Member,one-day delivery,21,3260,155
10,19340,1769953196,2013-10-13,Shirts,Male,Web,Clothing,Member,one-day delivery,19,17837,939
11,19404,1568148818,2013-10-14,Shirts,Male,Web,Clothing,Member,one-day delivery,14,1016,73
12,19427,1751652831,2013-10-14,Shirts,Male,Web,Clothing,Member,one-day delivery,14,4628,331
13,19592,2231859892,2013-10-14,Shirts,Male,Web,Clothing,Member,one-day deliver,20,570,29
14,19932,1535745421,2013-10-15,Shirt,Male,Web,Clothing,Member,one-day deliver,12,3000,250
15,20055,1922087137,2013-10-15,Shirt,Male,Web,Clothing,Member,one-day deliver,22,5573,253
16,20315,2262467094,2013-10-15,Shirt,Male,Web,Clothing,Member,one-day deliver,19,5349,282
17,20321,2268641437,2013-10-15,Shirt,Male,Web,Clothing,Member,one-day deliver,16,2500,156
18,20436,1727052876,2013-10-15,Shirts,Male,Web,Clothing,Member,Normal Delivery,15,6900,460
19,20535,1674613702,2013-10-15,Shirts,Male,Web,Clothing,Member,one-day deliver,21,1794,85
20,20693,1921733731,2013-10-16,Shirts,Male,Web,Clothing,Member,one-day deliver,12,6000,500
21,22314,1936150747,2013-10-18,Shirts,Male,Web,Clothing,Member,one-day deliver,20,584,29
22,22421,1229841159,2013-10-18,Shirt,Male,Web,Clothing,Member,one-day deliver,21,5217,248
23,22458,1586690479,2013-10-19,Shirt,Male,Web,Clothing,Member,one-day deliver,13,300,23
24,22682,1848085677,2013-10-19,Shirt,Male,Web,Clothing,Member,one-day deliver,16,1999,125
25,22740,1872369353,2013-10-19,Shirt,Male,Web,Clothing,Member,one-day deliver,16,699,44
26,22907,1519749240,2013-10-19,Shirt,Male,Web,Clothing,Member,one-day deliver,18,499,28
27,23261,1439048077,2013-10-20,Shirt,Male,Web,Clothing,Member,one-day deliver,21,7395,352
28,23490,1361902722,2013-10-20,Shirt,Male,Web,Clothing,Member,one-day delivery,13,1999,154
29,23501,1535495415,2013-10-20,Shirt,Male,Web,Clothing,Member,one-day delivery,22,299,14
...,...,...,...,...,...,...,...,...,...,...,...,...
2780,67681,2238091027,2013-12-14,Shoes,Female,Mobile,wearables,Member,one-day deliver,12,500,42
2781,67790,1628206020,2013-12-14,Shoes,Female,Mobile,wearables,Member,one-day deliver,14,1000,71
2782,67897,1685924134,2013-12-14,Shoes,Female,Mobile,wearables,Member,one-day deliver,12,429,36
2783,68055,1686570943,2013-12-14,Shoes,Female,Mobile,wearables,Member,one-day deliver,21,4326,206
2784,69322,1442018926,2013-12-15,Shoes,Female,Mobile,wearables,Member,one-day deliver,17,995,59
2785,69325,2201147779,2013-12-15,Shoes,Female,Mobile,wearables,Member,one-day deliver,14,1610,115
2786,69773,1229801150,2013-12-15,Shoes,Female,Mobile,wearables,Member,one-day deliver,12,2495,208
2787,70230,1176645739,2013-12-16,Shoes,Female,Mobile,wearables,Member,one-day deliver,12,12881,1073
2788,72667,1612949281,2013-12-17,Shoes,Female,Mobile,wearables,Member,one-day deliver,22,2000,91
2789,73066,1429149492,2013-12-17,Shoes,Female,Mobile,wearables,Member,Normal Delivery,21,17099,814
2790,73183,1252460418,2013-12-18,Shoes,Female,Mobile,wearables,Member,one-day deliver,23,1499,65
2791,73741,1778837865,2013-12-18,Shoes,Female,Mobile,wearables,Member,one-day deliver,21,0,0
2792,74317,2293384527,2013-12-19,Shoes,Female,Mobile,wearables,Guest,one-day deliver,21,1000,48
2793,75234,1178375628,2013-12-20,Shoes,Female,Mobile,wearables,Member,one-day deliver,15,0,0
2794,77362,1638141469,2013-12-23,Shoes,Female,Mobile,wearables,Member,one-day deliver,14,23954,1711
2795,78016,1915952977,2013-12-24,Shoes,Female,Mobile,wearables,Member,one-day deliver,18,1225,68
2796,78050,1329814703,2013-12-24,Shoes,Female,Mobile,wearables,Member,one-day deliver,18,1498,83
2797,78121,1329814703,2013-12-24,Shoes,Female,Mobile,wearables,Member,one-day deliver,18,5000,278
2798,79506,1724582223,2013-12-26,Shoes,Female,Mobile,wearables,Member,one-day deliver,13,1349,104
2799,79779,1273461348,2013-12-26,Shoes,Female,Mobile,wearables,Member,one-day deliver,21,7405,353
2800,80218,1594121463,2013-12-27,Shoes,Female,Mobile,wearables,Member,one-day deliver,15,2049,137
2801,80953,1678935868,2013-12-28,Shoes,Female,Mobile,wearables,Member,Normal Delivery,17,1199,71
2802,82436,2223609361,2013-12-29,Shoes,Female,Mobile,wearables,Member,one-day deliver,13,963,74
2803,82895,2196869116,2013-12-30,Shoes,Female,Mobile,wearables,Member,one-day deliver,16,2999,187
2804,84652,1163574886,2014-01-01,Shoes,Female,Mobile,wearables,Member,one-day deliver,23,1894,82
2805,87229,1934341369,2014-01-04,Shoes,Female,Mobile,wearables,Member,one-day deliver,13,3495,269
2806,91945,1506256089,2014-01-11,Shoes,Female,Mobile,wearables,Member,one-day deliver,13,9900,762
2807,92063,1651310842,2014-01-11,Shoes,Female,Mobile,wearables,Member,one-day deliver,23,1768,77
2808,92458,2152149636,2014-01-12,Shoes,Female,Mobile,wearables,Member,one-day deliver,16,9216,576
2809,92660,1382338268,2014-01-12,Shoes,Female,Mobile,wearables,Member,one-day deliver,16,3298,206

In [22]:
transaction.to_csv('transaction (cleaned).csv')